version: '3.8'
services:
  db:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test1
  backend:
    build: ./backend
    container_name: backend
    restart: always # 재시작
    ports:  
      - 8080:8080
    depends_on:
      - db